apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: csecho-ingress
spec:
  rules:
  - http:
      paths:
      - path: /dev/csecho
        pathType: Prefix
        backend:
          service:
            name: csecho
            port:
              number: 80
